### ISSUE TITLE
"User Manual" Button in Help section of "QXmlEdit Guided Operations" window does not work.

### ISSUE THREAD

**Issue by frederickjh** [frederickjh/qxmledit#2]
![image](https://user-images.githubusercontent.com/864159/40257561-e07cf114-5aee-11e8-93aa-1be7931f557a.png)

**Comment by frederickjh** [comment]
When running `qxmledit` from the terminal the error that appears in the terminal when the button is clicked is: `user-open error: no such file or directory`.

**Comment by frederickjh** [comment]
We need a way to set the path that QXmlEdit looks for the PDF documentation file. I believe that this must include the **$SNAP** variable.
ie. `$SNAP/opt/qxmledit`.

**Comment by frederickjh** [comment]
There is more information regarding this issue on the issue I created on the upstream [lbellonda/qxmledit](https://github.com/lbellonda/qxmledit) project [#50](https://github.com/lbellonda/qxmledit/issues/50).

**Comment by frederickjh** [comment]
Asked for help in [lbellonda/qxmledit issue 57](https://github.com/lbellonda/qxmledit/issues/57#issuecomment-448770780) from the maintainer.

**Comment by frederickjh** [comment]
Information from [lbellonda/qxmledit issue 57](https://github.com/lbellonda/qxmledit/issues/57) about what, it appears, needs to be done upstream to be able to fix this issue.

> From other examples I need to be able to set the path to the directory that QXmlEdit looks to find the file at to $SNAP/opt/qxmledit. If you look at my snapcraft.yaml (and also the qxmledit.desktop file) you will see this is what I did so that the .desktop file could find the icon. I believe that the $SNAP variable will be set at runtime so that the path to the document file will be correct.

> **Can you add a qmake option to allow setting where QXmlEdit will look for the documentation file? It means that QXmlEdit will need to get the $SNAP environment variable at runtime.**

**Comment by brlin-tw** [comment]
Tweaking the installation prefix directory to $SNAP should work

**Comment by brlin-tw** [comment]
The actual code that open the manual: https://github.com/lbellonda/qxmledit/blob/11177dcc006afe883171ac369df9dc93222df4ac/src/applicationdata.cpp#L600-L604

**Comment by brlin-tw** [comment]
Some build configuration variables may help:  
https://github.com/lbellonda/qxmledit/blob/master/INSTALL
