### ISSUE TITLE
Need Testers

### ISSUE THREAD

**Issue by frederickjh** [frederickjh/qxmledit#3]
It has now been 2 1/2 months since I posted the [call for testing for the snap for QXmlEdit](https://forum.snapcraft.io/t/call-for-testing-qxmledit/7087) on the [Snapcraft forum](https://forum.snapcraft.io/).

There have been no responses. @lbellonda, do you think that you could let your community of users know that a beta snap for QXmlEdit is available for testing. So far the only known issue is that the help document fails to launch. The project that I was using QXmlEdit for has been put on hold so I am not using the snap much any more to test.
Thanks @lbellonda for any help you can give!

**Comment by lbellonda** [comment]
Hello, you can post a request to the QXmlEdit forum directly:
 https://groups.google.com/group/qxmledit-discuss

**Comment by frederickjh** [comment]
[Post](https://groups.google.com/forum/#!topic/qxmledit-discuss/jJ-Lu2Ze5Uc) on the QXmlEdit google group calling for testers.

**Comment by frederickjh** [comment]
It seems that some people have installed via the Snap, however as of yet no feedback.

![image](https://user-images.githubusercontent.com/864159/50365777-6200a500-0576-11e9-90a4-c87badf0d7c7.png)

**Comment by frederickjh** [comment]
I just released the latest version of QXmlEdit 0.9.12 in the beta channel of the snap store. This has a number of fixes including the documentation button should open the PDF documentation file. Please give feeback here in the [QXmlEdit Snap project's github issue queue](https://github.com/frederickjh/qxmledit/issues).

**Comment by frederickjh** [comment]
I am closing this as I have received no feedback and am no longer interested in getting any.
